version: "3.9"

services:
  nginx: 
    image: nginx:latest 
    container_name: nginx-server1
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
  attacker:
    build:
      context: ./attacker 
    container_name: attacker
    depends_on:
      - nginx
    command: tail -f /dev/null
  
  fluentd:
    image: fluent/fluentd:v1.16-debian-1
    container_name: fluentd-log-collector
    volumes:
      - ./logs/nginx:/var/log/nginx:ro
      - ./fluentd:/fluentd
      - ./fluentd/output:/fluentd/output
    environment:
      - FLUENTD_CONF=fluentd.conf

  
